package model.lexico;

public enum ClaseLexica {
    ENTERO, REAL, BOOLEAN, STRING, IDENTIFICADOR, LITERAL_ENTERO, LITERAL_REAL, LITERAL_TRUE, 
    LITERAL_FALSE, LITERAL_STRING, SUMA, RESTA, MULTIPLICACION, DIVISION, MODULO, AND, OR, NOT, MENOR, 
    MAYOR, MENOR_IGUAL, MAYOR_IGUAL, IGUAL, DIFERENTE, ASIGNACION, PYC, PAR_APERTURA, PAR_CIERRE, 
    COR_APERTURA, COR_CIERRE, LLAVE_APERTURA, LLAVE_CIERRE, COMA, ACCESO, EVALUA, EOF, CAMBIO_SEC, 
    ERROR, NULL, PROC, IF, ELSE, WHILE, STRUCT, NEW, DELETE, READ, WRITE, NL, TYPE, CALL, REFERENCIA,
    PUNTERO
}
