/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoTinyConstants.java */
package model.sintaxis;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorSintacticoTinyConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Letra = 1;
  /** RegularExpression Id. */
  int DigitoPositivo = 2;
  /** RegularExpression Id. */
  int Digito = 3;
  /** RegularExpression Id. */
  int ParteEntera = 4;
  /** RegularExpression Id. */
  int ParteDecimal = 5;
  /** RegularExpression Id. */
  int ParteExponencial = 6;
  /** RegularExpression Id. */
  int ComboPartes = 7;
  /** RegularExpression Id. */
  int Entero = 8;
  /** RegularExpression Id. */
  int Real = 9;
  /** RegularExpression Id. */
  int Boolean = 10;
  /** RegularExpression Id. */
  int String = 11;
  /** RegularExpression Id. */
  int LiteralTrue = 12;
  /** RegularExpression Id. */
  int LiteralFalse = 13;
  /** RegularExpression Id. */
  int And = 14;
  /** RegularExpression Id. */
  int Or = 15;
  /** RegularExpression Id. */
  int Not = 16;
  /** RegularExpression Id. */
  int Null = 17;
  /** RegularExpression Id. */
  int Proc = 18;
  /** RegularExpression Id. */
  int If = 19;
  /** RegularExpression Id. */
  int Else = 20;
  /** RegularExpression Id. */
  int While = 21;
  /** RegularExpression Id. */
  int Struct = 22;
  /** RegularExpression Id. */
  int New = 23;
  /** RegularExpression Id. */
  int Delete = 24;
  /** RegularExpression Id. */
  int Read = 25;
  /** RegularExpression Id. */
  int Write = 26;
  /** RegularExpression Id. */
  int Nl = 27;
  /** RegularExpression Id. */
  int Type = 28;
  /** RegularExpression Id. */
  int Call = 29;
  /** RegularExpression Id. */
  int Identificador = 30;
  /** RegularExpression Id. */
  int LiteralEntero = 31;
  /** RegularExpression Id. */
  int LiteralReal = 32;
  /** RegularExpression Id. */
  int LiteralString = 33;
  /** RegularExpression Id. */
  int Suma = 34;
  /** RegularExpression Id. */
  int Resta = 35;
  /** RegularExpression Id. */
  int Mul = 36;
  /** RegularExpression Id. */
  int Div = 37;
  /** RegularExpression Id. */
  int Modulo = 38;
  /** RegularExpression Id. */
  int Puntero = 39;
  /** RegularExpression Id. */
  int Referencia = 40;
  /** RegularExpression Id. */
  int MenorQue = 41;
  /** RegularExpression Id. */
  int MayorQue = 42;
  /** RegularExpression Id. */
  int MenorOIgualQue = 43;
  /** RegularExpression Id. */
  int MayorOIgualQue = 44;
  /** RegularExpression Id. */
  int Igual = 45;
  /** RegularExpression Id. */
  int Diferente = 46;
  /** RegularExpression Id. */
  int Asignacion = 47;
  /** RegularExpression Id. */
  int PyC = 48;
  /** RegularExpression Id. */
  int ParAp = 49;
  /** RegularExpression Id. */
  int ParCierre = 50;
  /** RegularExpression Id. */
  int CorcheteApertura = 51;
  /** RegularExpression Id. */
  int CorcheteCierro = 52;
  /** RegularExpression Id. */
  int LlaveApertura = 53;
  /** RegularExpression Id. */
  int LlaveCierre = 54;
  /** RegularExpression Id. */
  int Acceso = 55;
  /** RegularExpression Id. */
  int Coma = 56;
  /** RegularExpression Id. */
  int FinDeclaracion = 57;
  /** RegularExpression Id. */
  int Evalua = 58;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<Letra>",
    "<DigitoPositivo>",
    "<Digito>",
    "<ParteEntera>",
    "<ParteDecimal>",
    "<ParteExponencial>",
    "<ComboPartes>",
    "<Entero>",
    "<Real>",
    "<Boolean>",
    "<String>",
    "<LiteralTrue>",
    "<LiteralFalse>",
    "<And>",
    "<Or>",
    "<Not>",
    "<Null>",
    "<Proc>",
    "<If>",
    "<Else>",
    "<While>",
    "<Struct>",
    "<New>",
    "<Delete>",
    "<Read>",
    "<Write>",
    "<Nl>",
    "<Type>",
    "<Call>",
    "<Identificador>",
    "<LiteralEntero>",
    "<LiteralReal>",
    "<LiteralString>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\"&\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"=\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\".\"",
    "\",\"",
    "\"&&\"",
    "\"@\"",
    "<token of kind 59>",
    "<token of kind 60>",
  };

}
