
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package model.sintaxis;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int LITERAL_ENTERO = 7;
  public static final int POR = 14;
  public static final int PCIERRE = 29;
  public static final int LITERAL_REAL = 8;
  public static final int ENTERO = 2;
  public static final int DIFERENTE = 25;
  public static final int RESTA = 13;
  public static final int COR_CIERRE = 33;
  public static final int REFERENCIA = 51;
  public static final int WRITE = 47;
  public static final int DELETE = 45;
  public static final int IDENTIFICADOR = 6;
  public static final int NOT = 19;
  public static final int AND = 17;
  public static final int IGUAL = 24;
  public static final int TYPE = 49;
  public static final int OR = 18;
  public static final int CALL = 50;
  public static final int DIV = 15;
  public static final int SUMA = 12;
  public static final int IF = 40;
  public static final int EOF = 0;
  public static final int BOOLEAN = 4;
  public static final int EVALUA = 36;
  public static final int NEW = 44;
  public static final int error = 1;
  public static final int COMA = 34;
  public static final int MODULO = 16;
  public static final int NULL = 38;
  public static final int MENOR = 20;
  public static final int PUNTERO = 52;
  public static final int ASIGNACION = 26;
  public static final int REAL = 3;
  public static final int MAYOR = 21;
  public static final int PAP = 28;
  public static final int ELSE = 41;
  public static final int NL = 48;
  public static final int READ = 46;
  public static final int LLAVE_APERTURA = 30;
  public static final int LITERAL_STRING = 11;
  public static final int COR_APERTURA = 32;
  public static final int LITERAL_FALSE = 10;
  public static final int WHILE = 42;
  public static final int ACCESO = 35;
  public static final int MAYOR_IGUAL = 23;
  public static final int LLAVE_CIERRE = 31;
  public static final int PROC = 39;
  public static final int STRING = 5;
  public static final int MENOR_IGUAL = 22;
  public static final int STRUCT = 43;
  public static final int PYC = 27;
  public static final int CAMBIO_SEC = 37;
  public static final int LITERAL_TRUE = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "REAL",
  "BOOLEAN",
  "STRING",
  "IDENTIFICADOR",
  "LITERAL_ENTERO",
  "LITERAL_REAL",
  "LITERAL_TRUE",
  "LITERAL_FALSE",
  "LITERAL_STRING",
  "SUMA",
  "RESTA",
  "POR",
  "DIV",
  "MODULO",
  "AND",
  "OR",
  "NOT",
  "MENOR",
  "MAYOR",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "IGUAL",
  "DIFERENTE",
  "ASIGNACION",
  "PYC",
  "PAP",
  "PCIERRE",
  "LLAVE_APERTURA",
  "LLAVE_CIERRE",
  "COR_APERTURA",
  "COR_CIERRE",
  "COMA",
  "ACCESO",
  "EVALUA",
  "CAMBIO_SEC",
  "NULL",
  "PROC",
  "IF",
  "ELSE",
  "WHILE",
  "STRUCT",
  "NEW",
  "DELETE",
  "READ",
  "WRITE",
  "NL",
  "TYPE",
  "CALL",
  "REFERENCIA",
  "PUNTERO"
  };
}

